### ISSUE TITLE
Cachelite with one page

### ISSUE THREAD

**Issue by jdsimcoe** [symphonists/cachelite#21]
So I am trying to implement Cachelite on a site with all Datasources feeding into a single page. I have Symphony sections to handle different URLs and code that routes datasources and Conditionalizer turns them on for different URLs but there is only one base page in Symphony. How can I integrate Cachelite with my site? Will it know that all my datasources feed into a single page?

When I have tried using it in the past, upon saving entries in my sections it would not flush cache and I ended up having to abandon using it. Any ideas or pointers?

**Comment by nitriques** [comment]
All values from the `$_GET` superglobal are used to create the cache key. Maybe that's the problem. Closing for now.
