### ISSUE TITLE
Doesn't include changes performed by the "HTML5 Doctype" extension.

### ISSUE THREAD

**Issue by twiro** [symphonists/cachelite#26]
Just noticed that the cachelite extension doesn't seem to reflect the changes that the html5-doctype-extension performs.

As long as I am logged into symphony I am served valid html5-code, as soon as I log out cachelite seems to intercept the page output before html5-doctype performs its manipulations and therefore serves me the basic symphony xhtml-doctypes.

**My Setup:**
- Symphony 2.5.2
- Cachelite 1.3
- HTML5 Doctype 1.3.2

**Comment by twiro** [comment]
Just noticed this was filed as an [issue](https://github.com/symphonists/html5_doctype/issues/6) in the html5-doctype-repository 2 years ago... hence seems to be not an easy thing to fix :(

**Comment by andrewminton** [comment]
Using hard coded approach to page templates maybe a way around this.. @nathanhornby had a nice gist of his master template which came in real handy and avoided this doc type manipulation at runtime I think.

**Comment by brendo** [comment]
Yes unfortunately this exposes a limitation in the delegate system. Both cachelite and html5 doctype use the `FrontendPageResolved` delegate, but as the extensions are executed in alphabetical order, cachelite will go first, and then html5 doctype. This was originally raised as symphonycms/symphony-2#993.

Hopefully @andrewminton's comment is more helpful!

**Comment by twiro** [comment]
Thanks for your quick feedback!

So I could either rename my html5-doctype-extension to make it execute before the cachelite-extension or ditch that extension altogether and use other output methods like the one in nathans template... I guess I have to test both methods to see what suits me best - and maybe reread the whole [XSLT and HTML5 discussion](http://www.getsymphony.com/discuss/thread/43003/) to really understand the differences ;)

**Comment by nathanhornby** [comment]
@andrewminton That's the one - can't remember who provided the original technique for the template, but it's worked well for us over the years!

**Comment by nitriques** [comment]
@twiro [We have a html5 compatible master-page](https://github.com/DeuxHuitHuit/symphony-2-template/blob/master/workspace/utilities/master/master.xsl) too if you want to check for different implementations. Been using it since Symphony 2.1 :) 

I'll close the issue here since we can't do nothing for it right now (because of what @brendo said about delegates)
