### ISSUE TITLE
Cache Period doesn't work at all

### ISSUE THREAD

**Issue by ChoboHub** [symphonists/cachelite#32]
The method _cleanDir($dir, $group = false, $mode = 'ingroup'){ ... } never get called.

It starts with $_automaticCleaningFactor = 0

![starthere](https://cloud.githubusercontent.com/assets/8250836/17445882/b6971f4a-5b14-11e6-86bb-b4f650ae45f0.PNG)

Then when you go in the method save(..) {...} 

![tohere](https://cloud.githubusercontent.com/assets/8250836/17445958/17db934e-5b15-11e6-904a-36af76c466ce.PNG)

And nowhere in the extension folders, $_automaticCleaningFactor isn't increment to 1 or modify.

The method simply skip the $this->clean(false, 'old'); and never call it,
since $_automaticCleaningFactor = 0.

Here some screenshots of the save, clean and _cleanDir methods.

![savemethod](https://cloud.githubusercontent.com/assets/8250836/17446105/bcdeabec-5b15-11e6-83f2-02827cbb3030.PNG)

![cleanmethod](https://cloud.githubusercontent.com/assets/8250836/17446106/bf466564-5b15-11e6-99ec-c083cc948a8f.PNG)

![_cleandir](https://cloud.githubusercontent.com/assets/8250836/17446107/c2906b3e-5b15-11e6-937f-ac41c6b585e1.PNG)

**Comment by nitriques** [comment]
The files does not get purged, but the period is respected.
