### ISSUE TITLE
Update 1.3.3 -> 2.0.0 error Invalid default value for 'timestamp' 

### ISSUE THREAD

**Issue by wdebusschere** [symphonists/cachelite#37]
MySQL Error (1067): Invalid default value for 'timestamp' in query: CREATE TABLE `sym_cachelite_references` ( `page` char(128) NOT NULL, `section_id` int(11) NOT NULL default 0, `entry_id` int(11) NOT NULL default 0, `timestamp` datetime NOT NULL default CURRENT_TIMESTAMP, PRIMARY KEY (`page`, `section_id`, `entry_id`), KEY `page` (`page`), KEY `section_page` (`page`, `section_id`), KEY `entry_page` (`page`, `entry_id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

**Comment by nitriques** [comment]
Which version of MySQL ?

**Comment by wdebusschere** [comment]
Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.5.42 - Source distribution

Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/5.6.10 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $
PHP extension: mysqli Documentation
PHP version: 5.6.10

**Comment by nitriques** [comment]
Ok that's why `CURRENT_TIMESTAMP` is 5.6+. I'll check this out. It does fixes the bug if you remove it from the code ?

Change `datetime NOT NULL default CURRENT_TIMESTAMP` with `datetime NULL`

**Comment by wdebusschere** [comment]
Yes, no errors now

**Comment by nitriques** [comment]
Ok I'll fix this, thanks.

**Comment by nitriques** [comment]
When you can, please test 2984e0f. Simply uninstall and re-install the extension.

**Comment by wdebusschere** [comment]
Works!
