### ISSUE TITLE
Cachelite doesnt work on the default page

### ISSUE THREAD

**Issue by wdebusschere** [symphonists/cachelite#38]
http://www.oursite.be/nl/ (no caching)
http://www.oursite.be/nl/home/ same page, works..

**Comment by nitriques** [comment]
Hum how did you check that it's not working ? It's normal that both url have their own cache (it's url based). Also, make sure you have the latest frontend_language version.

**Comment by wdebusschere** [comment]
I check the comment in de source
I have the latest version of 
FLang detection gTLDs
Frontend Localisation
Frontend Localisation Redirection

**Comment by wdebusschere** [comment]
strange, without Excluded URLs it works also for the home

Excluded URLs: 
cms*
json*

**Comment by nitriques** [comment]
Hum I think I know why. I'll have to test this. Thanks.

**Comment by nitriques** [comment]
Should be fixed in `2.0.2` Can you confirm please ?

**Comment by wdebusschere** [comment]
perfect! Thank you @nitriques

**Comment by nitriques** [comment]
Great!
