### ISSUE TITLE
Excluded url's not working 100%

### ISSUE THREAD

**Issue by wdebusschere** [symphonists/cachelite#40]
We have tried to exclude our cms but doesn't seem to work 100%.. (we are not logged on to symphony). We need to disable caching when a member is logged in..
Would it be possible to have some more info about the excluded pages in combination with the languages extensions?

if we just add home it works for the home page not to be cached, but for cms this doesn't work, cms has several subpages.. tried cms* cms_* /en/cms*

Thanks

**Comment by nitriques** [comment]
>  We need to disable caching when a member is logged in..

this needs to be done in the member extension, see https://github.com/symphonists/cachelite#bypassing-the-cache

> cms*

*cms* that should work. en/cms* should also work. Which version are you running ?

**Comment by wdebusschere** [comment]
Yes, Pages denied to public members in  Page Level Permissions can't be excluded.
We use all last versions.
Could you tell me where to add the bypas code.

**Comment by nitriques** [comment]
> can't be excluded.

Meaning they are ALWAYS cached ?

> Could you tell me where to add the bypass code.

In the extension.driver.php file of the member extension. It needs to have a new method that is called by the delegate system.
